### ISSUE TITLE
treesit-jump/:catch: Symbol’s function definition is void: transient-prefix

### ISSUE THREAD

**Issue by elge70** [dmille56/treesit-jump#1]
Error (use-package): treesit-jump/:catch: Symbol’s function definition is void: transient-prefix

I am getting this when the package is initialized . I am using this config

(use-package treesit-jump
  :straight (:host github :repo "dmille56/treesit-jump" :files ("*.el" "treesit-queries"))
  :config
  ;; Optional: add some queries to filter out of results (since they can be too cluttered sometimes)
  (setq treesit-jump-queries-filter-list '("inner" "test" "param")))

on windows and ubuntu and get the same error. I am using emacs 29.2

**Comment by dmille56** [comment]
Hmm looks like i forgot to require transient and list it as a dependency... Went ahead and changed that.  Perhaps try again?

**Comment by elge70** [comment]
That error is not seen now. But I have another error

  Error (use-package): treesit-jump/:catch: Symbol’s function definition is void: \(setf\ map-elt\)_

**Comment by dmille56** [comment]
Ok yeah looks like the code needs a require for map too to solve that error... Went ahead and added it.

**Comment by elge70** [comment]
Package is working fine now. Is it possible to add tsx support (https://github.com/tree-sitter/tree-sitter-typescript/tree/master/tsx) ?
Thx

**Comment by dmille56** [comment]
Yeah there's queries for tsx already here https://github.com/dmille56/treesit-jump/tree/main/treesit-queries/tsx  (which should work tho I haven't tested them)... They'd just need to be mapped to a major mode to know when to use them... Which major mode is for tsx?

**Comment by elge70** [comment]
tsx is typescript with JSX extensions (tsx-ts-mode) . For react.js UI framework

**Comment by dmille56** [comment]
Ok yeah I added a mapping in this commit: https://github.com/dmille56/treesit-jump/commit/5c176026f323c8db6519304b139e964597bdc0b5 so should work with that mode now

**Comment by elge70** [comment]
Working perfectly now. Thx..

**Comment by elge70** [comment]
Hi, When I compared the scm files, I found it incomplete for tsx. I textobjects.scm
; inherits: _jsx,_typescript,ecma

_jsx directory is missing. Is it possible to use https://github.com/nvim-treesitter/nvim-treesitter-textobjects/tree/master/queries in this package? nvim has a complete set of queries...

**Comment by dmille56** [comment]
I'm not quite sure if they'd compile/run correctly... took the ones from here: https://github.com/meain/evil-textobj-tree-sitter/tree/master/treesit-queries originally since they work with treesit.  I think evil-textboj-tree-sitter uses the ones from there with the tree-sitter library (elisp library here: https://github.com/emacs-tree-sitter/elisp-tree-sitter) but this package is using treesit (with is in emacs core since v 29).

**Comment by kvaneesh** [comment]
https://github.com/doomemacs/doomemacs/issues/4142 I had to use  (eval-and-compile (require 'transient)) to fix the error.

**Comment by dmille56** [comment]
Hmm interesting seems that it needs that for when it's byte-compiled... Anyways I added the (eval-and-compile (require 'transient)) snippet to the latest commit: https://github.com/dmille56/treesit-jump/commit/ed02e4e26819b7fde389f00738db7d96bb6fe1ac

**Comment by kvaneesh** [comment]
Ok. Something else is needed for it to work. I did a fresh doomeacs setup and i had to delete the treesit-jump-autoloads.el file to get it working.

**Comment by dmille56** [comment]
Ok I'm not familiar with Doom emacs but sounds like there might be an issue with the autoloads then I haven't tried compiling the autoloads yet I'll have to see if there's an issue there
